#!/bin/env lua
-- vim:foldmethod=marker

--------------- 配置文件路径 ---------------
local files = {
	"nav/HomePage.yml",
	"nav/CS61A.yml",
	"nav/CS61B.yml",
	"nav/CS61C.yml",
	"nav/PA.yml",
	"nav/MIT6.S081.yml",
}
--------------------------------------------

-- {{{
function read_file(file_path, isnav)
	local file = io.open(file_path, "r")
	if not file then
		error("无法打开文件: " .. file_path)
	end
	local content
	if isnav then
		content = ""
		for line in file:lines() do
			content = content .. "  " .. line .. "\n"
		end
	else
		content = file:read("a")
	end
	file:close()
	return content
end

function nav_yaml(files)
	local merged_content = {}

	for _, file in ipairs(files) do
		local content = read_file(file, true)
		table.insert(merged_content, content)
	end

	return table.concat(merged_content)
end

local final_content = read_file("nav/header.yml") .. nav_yaml(files)

local output_file = io.open("mkdocs.yml", "w")
if output_file then
	output_file:write(final_content)
	output_file:close()
	print("mkdocs.yml 成功生成！")
else
	print("无法创建 mkdocs.yml 文件。")
end
-- }}}
